name: voca
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  intl: ^0.17.0
  freezed_annotation: ^2.2.0
  injectable: ^2.1.0
  get_it: ^7.2.0
  slang: ^3.11.1
  slang_flutter: ^3.11.0
  sqflite: ^2.2.4+1
  path: ^1.8.2
  provider: ^6.0.5
  card_swiper: ^2.0.4
  flutter_card_swiper: ^2.0.1
  url_launcher: ^6.1.10
  receive_intent: ^0.2.3
  equatable: ^2.0.5
  clock: ^1.1.1
  shared_preferences: ^2.1.0
  awesome_notifications: ^0.7.4+1
  firebase_crashlytics: ^3.1.1
  auto_route: ^7.1.0
  styled_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  injectable_generator: ^2.1.5
  sqflite_common_ffi: ^2.2.2
  auto_route_generator: ^7.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
