name: voca
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  intl: ^0.17.0
  intl_utils: ^2.7.0
  go_router: ^6.0.1

flutter_intl:
  enabled: true
  class_name: Intls
  main_locale: en
  arb_dir: lib/presentation/base/l10n
  output_dir: lib/presentation/base/l10n/gen

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
